services:

  postgres-user:
    image: postgres:17-alpine
    container_name: eco-postgres-user
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_password
    ports:
      - "5567:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user_service", "-d", "user_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres-inventory:
    image: postgres:17-alpine
    container_name: eco-postgres-inventory
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_service
      POSTGRES_PASSWORD: inventory_password
    ports:
      - "5568:5432"
    volumes:
      - postgres-inventory-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "inventory_service", "-d", "inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongodb-products:
    image: mongo:latest
    container_name: eco-mongodb-product
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: product_service
      MONGO_INITDB_ROOT_PASSWORD: product_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb-products-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: eco-redis
    ports:
      - "6679:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-user-data:
  redis-data:
  postgres-inventory-data:
  mongodb-products-data: